FROM python:3.12-slim

WORKDIR /app

COPY src/scheduler.py .
COPY data/processes.json ./data/

ENV INPUT_FILE=/app/data/processes.json

ENTRYPOINT ["python", "scheduler.py", "--algorithm", "rr", "--input", "/app/data/processes.json"]
CMD ["--quantum", "2"]